### ISSUE TITLE
Members Page

### ISSUE THREAD

**Issue by pauladam316** [waterloo-rocketry/wrt-site#16]
We need a page with photos of all the team members + short 1-2 sentence description about each person, written by that person.

**Comment by jbdeery** [comment]
might be nice to make all the photos standard (e.g. team shirts in E5 or something similar)

**Comment by pauladam316** [comment]
Yeah we need to do a proper photo booth to get consistent photos. Or we could do drawings like miranda has for your profile photo jacob, and do that for everyone
